# Generated by Django 5.0.6 on 2024-07-31 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0005_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('To do', 'To do'), ('In progress', 'In progress'), ('Await feedback', 'Await feedback'), ('Done', 'Done')], max_length=15),
        ),
    ]
