# Generated by Django 5.2 on 2025-04-06 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0007_subtask_done'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='assignedTo',
            new_name='assigned_to',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='dueDate',
            new_name='due_date',
        ),
    ]
